### PR TITLE
Fix phone validation

### LINKED ISSUE #221: incorrect function called for phone validation causes assertion error

### PR DESCRIPTION
**Pull request by weiseng18**
Closes #221

The issue was that, for phone validation we should call the `isValidPhoneField` function instead of the `isValidPhone` function. By calling `isValidPhone` function directly with the `phone` field, we may pass in a string with spaces directly, causing the assertion to trigger.

### CODE REVIEW

File: src/main/java/seedu/address/model/person/Phone.java [hunk 1]
```diff
@@ -35,7 +35,7 @@ public Phone(String phone) {
      * Our definition of a valid phone number is a string without spaces that has
      * at least 3 digits, and no alphabets.
      */
-    public static boolean isValidPhone(String test) {
+    static boolean isValidPhone(String test) {
```
Comment (weiseng18) [inline src/main/java/seedu/address/model/person/Phone.java:38]: thanks @lithops-zty for the great idea to make this package private!

**Review by lithops-zty — APPROVED** [review]
👍
