### PR TITLE
Fix allow same phone mail

### LINKED ISSUE #154: `edit` can change both phone and email to be exactly the same as someone else

### PR DESCRIPTION
**Pull request by Elinengu**
Closes #154 

The reason why the original if else statement does not work is that, as the the ``isSamePerson`` check if there is the same email or same phone number, hence in this statement:
```Java
        if (!personToEdit.isSamePerson(editedPerson) && model.hasPerson(editedPerson)) {
            throw new CommandException(MESSAGE_DUPLICATE_PERSON);
        }
```
The duplicate email/phone number can by pass the ``hasPerson`` check if the original phone number or email remains unchanged.

### CODE REVIEW

File: src/main/java/seedu/address/model/AddressBook.java [hunk 1]
```diff
@@ -67,6 +67,22 @@ public boolean hasPerson(Person person) {
...
+    /**
+     * Returns true if a person with the same phone number as {@code person} exists in the address book.
+     */
+    public boolean hasPhone(Person person) {
+        requireNonNull(person);
+        return persons.containsPhone(person);
+    }
+
+    /**
+     * Returns true if a person with the same phone number as {@code person} exists in the address book.
```
Comment (MAOXIONGKAI) [inline src/main/java/seedu/address/model/AddressBook.java:79]: The comment is not updated, it should be `with the same email`

**Review by MAOXIONGKAI — CHANGES_REQUESTED** [review]
LGTM! 👍 There's only one small mistake in the comment, after fixing that this PR is good to go!

File: src/main/java/seedu/address/model/AddressBook.java (hunk 1 above)
Comment (Elinengu) [reply src/main/java/seedu/address/model/AddressBook.java]: Fixed.

File: src/main/java/seedu/address/logic/commands/edit/EditCommand.java [hunk 2]
```diff
@@ -90,8 +91,15 @@ public CommandResult execute(Model model) throws CommandException {
         Person personToEdit = lastShownList.get(index.getZeroBased());
         Person editedPerson = createEditedPerson(personToEdit, editPersonDescriptor);
 
-        if (!personToEdit.isSamePerson(editedPerson) && model.hasPerson(editedPerson)) {
+        boolean phoneExists = model.hasPhone(editedPerson);
+        boolean emailExists = model.hasEmail(editedPerson);
```
Comment (weiseng18) [inline src/main/java/seedu/address/logic/commands/edit/EditCommand.java:95]: might want to rename these variables, `phoneExists` can mean inside the `Person` or inside the `Model`

so maybe something like `phoneIsFoundInModel` or list or something along those lines, and same for email

File: src/main/java/seedu/address/logic/commands/edit/EditCommand.java [hunk 3]
```diff
@@ -90,8 +91,15 @@ public CommandResult execute(Model model) throws CommandException {
...
+
+        if (!personToEdit.isSamePerson(editedPerson) && phoneExists && emailExists) {
             throw new CommandException(MESSAGE_DUPLICATE_PERSON);
```
Comment (weiseng18) [inline src/main/java/seedu/address/logic/commands/edit/EditCommand.java:98]: hmm actually maybe we can skip this check? because i think saying "this person already exists" is less meaningful than telling them that the phone number already exists or the email already exists

**Review by weiseng18 — APPROVED** [review]
lgtm
